# Generated by Django 3.2.4 on 2021-06-27 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default='acer', max_length=100),
            preserve_default=False,
        ),
    ]
